version: "3"

services:
  pushgateway:
    network_mode: host
    image: prom/pushgateway:v0.6.0
    ports:
      - 9091:9091
  prometheus:
    network_mode: host
    image: prom/prometheus:v2.3.2
    ports:
      - 9090:9090
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    network_mode: host
    image: grafana/grafana:5.2.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    user: "root" # starts container as root
    volumes:
      - ./data/grafana:/var/lib/grafana
